import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";

import Navbar from "./components/Navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
         <Head> 
          <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet" />
         </Head> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header><Navbar/></header>
      
  
        {children}
      </body>
    </html>
  );
}
